### ISSUE TITLE
Unable to stop/delete jobs on https://openeofed.dataspace.copernicus.eu/

### ISSUE THREAD

**Issue by HansVRP** [Open-EO/openeo-aggregator#141] opened 2024-05-16 07:56 UTC
<img width="689" alt="Capture" src="https://github.com/Open-EO/openeo-aggregator/assets/57984106/e72fa2fb-8db7-48c1-b7cb-c38a14828edd">

**Comment by soxofaan** [comment] 2024-05-29 15:52
duplicate of
- #39

**Closed** 2024-06-28 13:28 UTC
